# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "replay_cols", # <mr_make_17lands_schema>
  "regex", # <mr_make_17lands_schema>
  "arrow_type", # <mr_make_17lands_schema>
  "replay_col_name", # <mr_make_17lands_schema>
  NULL
))
